### ISSUE TITLE
Headless GUI Test Fails on Windows

### ISSUE THREAD

**Issue by AdamCarroll** [Santulator/Santulator#14]
The headless GUI test that works on Mac and Linux, fails on Windows.  If instead the build is launched with the `-PnoHeadless`, the build works without problems.

This was tested with OpenJDK 11.0.2 (AdoptOpenJDK) on Windows 10.  The error is as follows:
~~~
C:\Users\vagrant\Desktop\GitRepos\Santulator>gradlew test

> Task :gui:test
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe864a4879, pid=2380, tid=4276
#
# JRE version: OpenJDK Runtime Environment (11.0.2+9) (build 11.0.2+9)
# Java VM: OpenJDK 64-Bit Server VM (11.0.2+9, mixed mode, tiered, compressed oops, serial gc, windows-amd64)
# Problematic frame:
# C  [javafx_font.dll+0x4879]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\vagrant\Desktop\GitRepos\Santulator\gui\hs_err_pid2380.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:52524'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:135)
        at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:325)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
        at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:273)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:261)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:255)
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:133)
        ... 7 more

> Task :gui:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gui:test'.
> Process 'Gradle Test Executor 13' finished with non-zero exit value 1
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the User Manual at https://docs.gradle.org/5.2.1/userguide/java_testing.html#sec:test_execution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s
18 actionable tasks: 1 executed, 17 up-to-date
~~~

**Comment by AdamCarroll** [comment]
The key detail in the error message.  Seems to be this part:
~~~
# Problematic frame:
# C  [javafx_font.dll+0x4879]
~~~

It looks like the problem is caused by the following bug in OpenJFX on Windows: https://github.com/javafxports/openjdk-jfx/issues/66.  The good news is that it appears from the report that the problem is fixed in OpenJFX 12, which has just been released.

Santulator isn't yet ready to move to OpenJFX 12 (this is not an LTS release so it's not clear if this is the right thing to do).  Additionally, to make the change a, new version of Monocle for OpenJFX 12 will be required.  Once this is available, it should be possible to test the bug fix by changing the following two dependency versions:
* OpenJFX: https://github.com/Santulator/Santulator/blob/1a38e7565abbd21fcd5c0b45bfac9e19a4db846b/gui/build.gradle#L64
* Monocle: https://github.com/Santulator/Santulator/blob/1a38e7565abbd21fcd5c0b45bfac9e19a4db846b/gui/build.gradle#L57

**Comment by fsilkswan** [comment]
Encountered this bug in OpenJFX 12.0.1 as well. Sorry guys. (-_-)'

**Comment by AdamCarroll** [comment]
Thanks for the info @fsilkswan. It's interesting to know that it's fixed in OpenJFX 13.  I'm not sure what the compatibility of that is with JDK 11.  I see from your comment that you're using JDK 12.  One to experiment with when I get some free time I think.

**Comment by fsilkswan** [comment]
@AdamCarroll I'm sorry that I may post may be misleading. The error occured also while using "OpenJDK 12.0.0+12" and corresponding  "OpenJFX 12.0.1".
Then I switched my project to "OpenJDK 13" and "OpenJFX 13". In the latter constellation the bug no longer occurred.
I hope it is a little clearer now. ;)

**Comment by AdamCarroll** [comment]
Thanks for the clarification @fsilkswan!  And good luck with your JavaFX project.

**Comment by AdamCarroll** [comment]
This has been fixed by updating the versions of JavaFX and Monocle.  See this commit for details: 3760a34be455d871a8eb07e8b3ad2f000fa2e867
